package Formularios;

public class FormInstruccionesExamen extends javax.swing.JFrame {

    public String numAlumno;
    /**
     * Creates new form FormExamenAlumno
     */
    public FormInstruccionesExamen() {
        initComponents();
    }
    
    public FormInstruccionesExamen(String numAlumno1){
        initComponents();
        txtInstrucciones.setEditable(false);
        numAlumno = numAlumno1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInstrucciones = new javax.swing.JTextArea();
        btnEmpezar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/prueba.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Instrucciones");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1600, 10));

        txtInstrucciones.setColumns(20);
        txtInstrucciones.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        txtInstrucciones.setRows(5);
        txtInstrucciones.setText("1. El estudiante no puede usar su libro de texto, notas del curso o recibir ayuda de un supervisor o cualquier otra fuente externa.\n\n2. Los estudiantes deben completar el examen de opción múltiple de 10 preguntas dentro del marco de tiempo de 10 minutos \n    asignado para el examen.\n\n3. Los estudiantes no deben detener la sesión y el regreso a la misma. Esto es especialmente importante en el entorno en línea \n   donde el sistema \"agotará el tiempo de espera\" y no permitirá que el estudiante o usted vuelvan a ingresar al examen.\n\n\n* Número de preguntas: 10\n* Duración del examen: 10 minutos\n\t\t\t\t\n\n\t\t\t\t¡Mis mejores deseos!");
        jScrollPane1.setViewportView(txtInstrucciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 1310, 490));

        btnEmpezar.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        btnEmpezar.setText("Iniciar Examen");
        btnEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpezarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEmpezar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 780, 459, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/FondoDatosEstudiante.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpezarActionPerformed
        setVisible(false);
        new FormExamenAlumno(numAlumno).setVisible(true);
    }//GEN-LAST:event_btnEmpezarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormInstruccionesExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormInstruccionesExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormInstruccionesExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormInstruccionesExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormInstruccionesExamen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmpezar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea txtInstrucciones;
    // End of variables declaration//GEN-END:variables
}
