package Formularios;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class FormPanelProfesor extends javax.swing.JFrame {
    public static int abrir = 0;
    /**
     * Creates new form panelProfesor
     */
    public FormPanelProfesor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnAgregarPregunta = new javax.swing.JMenu();
        btnActualizarPregunta = new javax.swing.JMenu();
        btnEliminarPregunta = new javax.swing.JMenu();
        btnVerPreguntas = new javax.swing.JMenu();
        btnResultados = new javax.swing.JMenu();
        btnCerrarSesion = new javax.swing.JMenu();
        btnSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Fondo_Panel_Profesor.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -120, 1600, -1));

        jRadioButton1.setText("jRadioButton1");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 130, -1, -1));

        jMenuBar1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Barra de Navegación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 36), new java.awt.Color(51, 102, 0))); // NOI18N

        btnAgregarPregunta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/agregar-archivo.png"))); // NOI18N
        btnAgregarPregunta.setText("Agregar Pregunta");
        btnAgregarPregunta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregarPregunta.setMargin(new java.awt.Insets(0, 5, 0, 30));
        btnAgregarPregunta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarPreguntaMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnAgregarPregunta);

        btnActualizarPregunta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/actualizar.png"))); // NOI18N
        btnActualizarPregunta.setText("Actualizar Pregunta");
        btnActualizarPregunta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizarPregunta.setMargin(new java.awt.Insets(0, 5, 0, 30));
        btnActualizarPregunta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarPreguntaMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnActualizarPregunta);

        btnEliminarPregunta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/expediente.png"))); // NOI18N
        btnEliminarPregunta.setText("Eliminar Pregunta");
        btnEliminarPregunta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarPregunta.setMargin(new java.awt.Insets(0, 5, 0, 30));
        btnEliminarPregunta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarPreguntaMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnEliminarPregunta);

        btnVerPreguntas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/portapapeles.png"))); // NOI18N
        btnVerPreguntas.setText("Lista Preguntas");
        btnVerPreguntas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerPreguntas.setMargin(new java.awt.Insets(0, 5, 0, 30));
        btnVerPreguntas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerPreguntasMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnVerPreguntas);

        btnResultados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/los-grados.png"))); // NOI18N
        btnResultados.setText("Resultados de los estudiantes");
        btnResultados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnResultados.setMargin(new java.awt.Insets(0, 5, 0, 30));
        btnResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResultadosMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnResultados);

        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Logout.png"))); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrarSesion.setMargin(new java.awt.Insets(0, 5, 0, 30));
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnCerrarSesion);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/salida.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalir.setMargin(new java.awt.Insets(0, 5, 0, 30));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnSalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseClicked
        JFrame jframe = new JFrame();
        jframe.setAlwaysOnTop(true);
        int login = JOptionPane.showConfirmDialog(jframe, "¿Deseas realmente cerrar sesión?","Selecciona",JOptionPane.YES_NO_OPTION);
        if(login == 0){
            setVisible(false);
            new FormLoginProfesor().setVisible(true);
        }
    }//GEN-LAST:event_btnCerrarSesionMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        JFrame jframe = new JFrame();
        jframe.setAlwaysOnTop(true);
        int salir = JOptionPane.showConfirmDialog(jframe, "¿Deseas realmente salir del programa?","Selecciona",JOptionPane.YES_NO_OPTION);
        if(salir == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnAgregarPreguntaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarPreguntaMouseClicked
        if(abrir==0){
            new FormAgregarPregunta().setVisible(true);
            abrir=1;
        }else{
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, "Ya está abierto un formulario");
        }
    }//GEN-LAST:event_btnAgregarPreguntaMouseClicked

    private void btnActualizarPreguntaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarPreguntaMouseClicked
       if(abrir==0){
            new FormActualizarPregunta().setVisible(true);
            abrir=1;
        }else{
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, "Ya está abierto un formulario");
        }
    }//GEN-LAST:event_btnActualizarPreguntaMouseClicked

    private void btnVerPreguntasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerPreguntasMouseClicked
        if(abrir==0){
            new FormListaPreguntas().setVisible(true);
            abrir=1;
        }else{
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, "Ya está abierto un formulario");
        }
    }//GEN-LAST:event_btnVerPreguntasMouseClicked

    private void btnEliminarPreguntaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarPreguntaMouseClicked
        if(abrir==0){
            new FormBorrarPregunta().setVisible(true);
            abrir=1;
        }else{
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, "Ya está abierto un formulario");
        }
    }//GEN-LAST:event_btnEliminarPreguntaMouseClicked

    private void btnResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResultadosMouseClicked
        if(abrir==0){
            new FormListaEstudiantes().setVisible(true);
            abrir=1;
        }else{
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, "Ya está abierto un formulario");
        }
    }//GEN-LAST:event_btnResultadosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPanelProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPanelProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPanelProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPanelProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPanelProfesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnActualizarPregunta;
    private javax.swing.JMenu btnAgregarPregunta;
    private javax.swing.JMenu btnCerrarSesion;
    private javax.swing.JMenu btnEliminarPregunta;
    private javax.swing.JMenu btnResultados;
    private javax.swing.JMenu btnSalir;
    private javax.swing.JMenu btnVerPreguntas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables
}
