package Formularios;

import java.sql.Connection;
import Proyecto.Conexion;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class FormActualizarPregunta extends javax.swing.JFrame {

    /**
     * Creates new form FormActualizarPregunta
     */
    public FormActualizarPregunta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtOpcion3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtEnunciado = new javax.swing.JTextField();
        txtOpcion1 = new javax.swing.JTextField();
        txtOpcion4 = new javax.swing.JTextField();
        btnCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtRespuesta = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnBuscarPregunta = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnActualizarPregunta = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtOpcion2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        txtBuscarPregunta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtBuscarPregunta2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(150, 183));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtOpcion3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(txtOpcion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 652, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel9.setText("Opción 4:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel10.setText("Respuesta:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, -1, -1));

        txtEnunciado.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(txtEnunciado, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 652, -1));

        txtOpcion1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(txtOpcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 652, -1));

        txtOpcion4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(txtOpcion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 652, -1));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Close.png"))); // NOI18N
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 67, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/actualizar.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtRespuesta.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(txtRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 652, -1));

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/limpieza-de-datos.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 480, -1, -1));

        btnBuscarPregunta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBuscarPregunta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/search.png"))); // NOI18N
        btnBuscarPregunta.setText("Buscar");
        btnBuscarPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPreguntaActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setText("Pregunta N°:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setText("Opción 3:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        btnActualizarPregunta.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnActualizarPregunta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/salvar.png"))); // NOI18N
        btnActualizarPregunta.setText("Actualizar");
        btnActualizarPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarPreguntaPreguntaActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizarPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setText("Opción 1:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel2.setText("Actualizar Pregunta");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 13, -1, -1));

        txtOpcion2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(txtOpcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 652, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setText("Opción 2:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 76, 1066, 10));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setText("Enunciado:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));
        getContentPane().add(txtBuscarPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 180, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondoPapel.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(txtBuscarPregunta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 180, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        FormPanelProfesor.abrir = 0;
        setVisible(false);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnBuscarPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPreguntaActionPerformed
        String idPregunta = txtBuscarPregunta.getText();

        try {
            Connection con = new Conexion().conectar();
            Statement statement = con.createStatement();
            ResultSet rs = statement.executeQuery("SELECT * FROM pregunta WHERE idPregunta='" + idPregunta + "'");

            if (rs.next()) {
                txtEnunciado.setText(rs.getString(2));
                txtOpcion1.setText(rs.getString(3));
                txtOpcion2.setText(rs.getString(4));
                txtOpcion3.setText(rs.getString(5));
                txtOpcion4.setText(rs.getString(6));
                txtRespuesta.setText(rs.getString(7));
                txtBuscarPregunta.setEditable(false);
            } else {
                JFrame jf = new JFrame();
                jf.setAlwaysOnTop(true);
                JOptionPane.showConfirmDialog(jf, "La pregunta que busca no existe");
            }

        } catch (Exception e) {
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showConfirmDialog(jf, e);
        }
    }//GEN-LAST:event_btnBuscarPreguntaActionPerformed

    private void btnActualizarPreguntaPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPreguntaPreguntaActionPerformed
        String id = txtBuscarPregunta.getText();
        String nombre = txtEnunciado.getText();
        String opcion1 = txtOpcion1.getText();
        String opcion2 = txtOpcion2.getText();
        String opcion3 = txtOpcion3.getText();
        String opcion4 = txtOpcion4.getText();
        String respuesta = txtRespuesta.getText();

        try {
            Connection con = new Conexion().conectar();
            PreparedStatement ps = con.prepareStatement("UPDATE pregunta set nombre=?,opcion1=?,opcion2=?,opcion3=?,opcion4=?,respuesta=? WHERE idPregunta=?");
            
            ps.setString(1, nombre);
            ps.setString(2, opcion1);
            ps.setString(3, opcion2);
            ps.setString(4, opcion3);
            ps.setString(5, opcion4);
            ps.setString(6, respuesta);
            ps.setString(7, id);

            ps.executeUpdate();

            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, "Pregunta actualizada correctamente!");
            setVisible(false);
            new FormActualizarPregunta().setVisible(true);

        } catch (Exception e) {
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showConfirmDialog(jf, e);
        }
    }//GEN-LAST:event_btnActualizarPreguntaPreguntaActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtEnunciado.setText("");
        txtOpcion1.setText("");
        txtOpcion2.setText("");
        txtOpcion3.setText("");
        txtOpcion4.setText("");
        txtRespuesta.setText("");
        txtBuscarPregunta.setEditable(true);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormActualizarPregunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormActualizarPregunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormActualizarPregunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormActualizarPregunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormActualizarPregunta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarPregunta;
    private javax.swing.JButton btnBuscarPregunta;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtBuscarPregunta;
    private javax.swing.JTextField txtBuscarPregunta2;
    private javax.swing.JTextField txtEnunciado;
    private javax.swing.JTextField txtOpcion1;
    private javax.swing.JTextField txtOpcion2;
    private javax.swing.JTextField txtOpcion3;
    private javax.swing.JTextField txtOpcion4;
    private javax.swing.JTextField txtRespuesta;
    // End of variables declaration//GEN-END:variables
}
